### ISSUE TITLE
我和我的朋友们可以借用你的服务器吗

### ISSUE THREAD

**Issue by xxxyouthxxx** [Narizgnaw/palworldgames#1]
本想和好友一起游玩 奈何囊中羞涩 只能求助于你

**Comment by moumoukings** [comment]
我也有这个想法，不知道作者后续是怎么计划的？

**Comment by Narizgnaw** [comment]
> 本想和好友一起游玩 奈何囊中羞涩 只能求助于你

可以可以，目前服务器人数少于20人，如果超过20人，我会加上密码。
